development:
  secret_key_base: secret_key_base
  foursquare_client_id: foursquare_client_id
  foursquare_client_secret: foursquare_client_secret

test:
  secret_key_base: secret_key_base

production:
  secret_key_base: secret_key_base
